### ISSUE TITLE
Ternary operator 

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#10]
```
myValue = (false) ? "value1" : "value2"

print myValue 
' Output: value2
```

**Comment by georgejecook** [comment]
I propose that ternary:

- Is for expressions only, as we overload ? (print) which is a statement 
- we replace ternary code with a generated function call

e.g 
```
function foo()
a =  isValid ? "yes" : "no"
end function

``````

becomes
function foo()
a = bs_tern_filename(isValid, "yes", "no")
end function

function bs_tern_filename_1(test, trueValue, falseValue)
 if test then return trueValue else return falseValue
end function

end function
```

I propose that we generate a function for each file that has a ternary operator and namespace it to the file's name.  Later on, when we have import support, we will simply use a runtime library function like `iff`, which we know is guaranteed to be in scope.

**Comment by georgejecook** [comment]
hey @TwitchBronBron I'd like to have a pop at this..

The only outstanding question I have is, how will we provide functions for the stdlib?

Coz I'm going to have to write this function and store it somewhere.

Can we also assume standard lib is included in all scopes?

**Comment by georgejecook** [comment]
Hope you don't mind me assigning it to myself; as per my pm on slack, I want to work on this at the weekend

**Comment by TwitchBronBron** [comment]
It's funny I was _just_ thinking about ternary tonight and ran into a few roadblocks. 

We can't just call a function because only the _matched_ expression should be evaluated. For example,

` isAlive = true ? doAliveThing(1) : m.getUndead().doZombieThing(2)`

If we transpile to a regular function call like this:

`bs_ternary(isAlive = true, doAliveThing(), m.getUndead().doZombieThing(2))`

then we have evaluated the expression for true _and_ the expression for false. That can cause unexpected side effects, and that's not how ternary in other languages work. 

One solution could be to capture all of the local variables and pass them in as some type of scope object. The transpiler would be smart enough to only pass in the variables referenced by the expressions. 

_BrighterScript_
```
sub main()
    age = 42
    humanName = "John"
    zombieName "zJohnz"
    isAlive = true ? doAliveThing(humanName) : doZombieThing(zombieName)
end sub
```

_Transpiled_
```
sub main()
    humanName = "John"
    zombieName "zJohnz"
    bs_ternary(isAlive = true, 
        'scope containing all variables used in the ternary expressions
        {
            humanName: humanName,
            zombineName: zombieName
        }, 
        'function for true
        function(scope)
            humanName = scope.humanName
            return doAliveThing(humanName)
        end function, 
        'function for false
        function(scope)
            zombieName = scope.zombieName
            return doZombieThing(zombieName)
        end function
    )
end sub

function bs_ternary(isTrue, scope, trueFunc, falseFunc)
    if isTrue then
        return trueFunc(scope)
    else
        return falseFunc(scope)
    end if
end function
````

**Comment by georgejecook** [comment]
I'd rather just put the if inline... Doing this scope grabbing is something want to do for async; but for ternary I'd be worried for performance impact doing this kind of thing.

Putting inline is no big deal. The more ram argument is moot coz we are only writing the same if statement a developer would write. 

We can iterate in future and call out to functions when we know true and false values are both non method invoking expressions, so as to offer better than handcoded ram usage.

Substituting the ternary value with an if statement on the previous line (for example in cases where we have a ternary in an of or else or for or while loop condition) will be far less code manipulation than the scope grabbing, as well.

**Comment by TwitchBronBron** [comment]
Problem is, creating an if statement on the previous line will cause its own issues. consider this:

```BrightScript
incrementor = {
    value : 0,
    getNext : function()
        m.value++
        return m.value
    end function
}

doSomething(incrementor.getNext(), isTrue ? incrementor.getNext(): -1)
```

I would expect `doSomething(1, 2)`. However, when we lift the ternary if statement to the previous line, we end up with `doSomething(2, 1)` because it transpiles like this:

_Transpiled_
```BrightScript
if true then
    bs_tern_value1 = incrementor.getNext() ' gets called first and returns 1
else
    bs_tern_value1 = -1
end if
'           gets called SECOND
doSomething(incrementor.getNext(), bs_tern_value1)
```

**Comment by TwitchBronBron** [comment]
>We can iterate in future and call out to functions when we know true and false values are both non method invoking expressions, so as to offer better than handcoded ram usage.

Yes for sure! In this situation we can definitely detect non function calls and call something like `bslib_ternarySimple(condition, trueValue, falseValue)`.   
<br>
>Substituting the ternary value with an if statement on the previous line (for example in cases where we have a ternary in an if or else or for or while loop condition) will be far less code manipulation than the scope grabbing, as well.

I don't think this point matters much, because we transpile the entire file from AST, so there's no code manipulation whatsoever anyway. We would be creating the code from scratch based on the AST.

**Comment by georgejecook** [comment]
btw, I very much like the human vs zombie theme here, and shall be adopting it. more memorable than foo vs bar.

**Comment by georgejecook** [comment]
started making progress as per your guidance, @TwitchBronBron .. problem I'm seeing..

how do we know if this is a statement or an assignment?

```a = true ? {"a":"a"} : {"b":"b"}```

as I see it, we have 2 options

1. Implement `==` in the language; I don't think that's a rash thing we can decide, and will derail adoption
2. Disable your use case above of ternary as a statement - as it goes for me that's a pr failure anyhow (I know, I have my ways); so I'm happy to have ternary is an expression only.

I think we should go with 2. I'll keep on trucking with transpiling.

**Comment by georgejecook** [comment]
on the note of transpiling, before I duplicate any work - do you have any uitility functions to mine all of the variable expressions and dotted get expressions from an expression?

it's a useful utility we will need for async await and null coalesence, too (at the very least).

Any guidance here? it's going to be a pig to get these out of all the various expression types? I almost wonder if Expression should have an abstract function for this..

Thoughts?

**Comment by georgejecook** [comment]
I wrote a util method for getting the var names. now the hard bit is renaming m, coz all `m.method` calls need to be `thatM.method`.. I might just regex replace in translate method for now; till we have something better, coz renaming m on every expressoin's transpose does not seem right. I'll fiddle with it early tomrrow.

**Comment by TwitchBronBron** [comment]
The problem with regex replacement is you'll need to make sure you support source maps, which might not work so well if you're just doing string replacements. However, it might not be so bad. 

There's also this method in util that might help you find things that start with `m`: https://github.com/rokucommunity/brighterscript/blob/master/src/util.ts#L451

Just keep in mind, the AST is reused when in watch mode, so any changes you make to the AST itself during transpile need to be undone after the transpile, otherwise it'll screw up the validation the next time the user changes some source code.

**Comment by TwitchBronBron** [comment]
Feel free to open a PR so I can start looking at your implementation awhile.

**Comment by georgejecook** [comment]
you didn't respond to me saying that conditional statements are not possible, becuase we can't infer assignment/vs equality.

I see no way around that so I'll remove it.

**Comment by TwitchBronBron** [comment]
with respect to assignment statements, we might just need to do a little more extensive lookahead?

**Comment by TwitchBronBron** [comment]
Because if we look ahead enough, or try to parse a conditional expression first and then look ahead for a question mark, that should be enough right?

**Comment by georgejecook** [comment]
I don't think it matters how far you look ahead: 

`a = myValue ? "a" : "b"
is both valid as ternary and as assignment to be

assignment :
`a = (myValue ? "a" : "b'")`

ternary:
`a = myValue ? "a" : "b"`

so, we can still support ternary statements; but we'd need to add some concessions:

 - implement `==` - totally opposed to this
 - enforce brackets for assignment; I'd not like this at all

I've pondered a few other options; but they ultimately are dead ends. Irrespective; I suggest we narrow the scope of this to ternary expressions now, and worry about the ternary statements later.

**Comment by georgejecook** [comment]
happy.. I've just pushed up a fairly complete version of it..
it does what you wanted, and I tested the following: - we can pass (and assign) `m` on scope.. so we don't have to rename anything :)

I wrote a couple of util methods to walk an expression; so it was easy to get all vars, and acertain if we have potential side effects; we use the latter to decide to use the light bslib ternary function or the heavier scoped one.

I've not actually tested the transpile bit - need to look at how you invoke this and setup scope elsewhere; but this isn't far off being done. test coverage is fairly good; if I'm not too far off form where you want, I'd be glad to move onto the other stuff..

**Comment by georgejecook** [comment]
and I just pushed up again - realized, I need to at least be managing an array of string|sourcenode

**Comment by TwitchBronBron** [comment]
Oh, I see now. Thanks for the examples with parenthesis. Yeah, we are gonna need to think a little harder about how to handle that. I agree, let's stick with expressions for now

**Comment by chrisdp** [comment]
This is done now isn't it?

**Comment by TwitchBronBron** [comment]
Yep!
