### ISSUE TITLE
AST tweaks

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1044]
Here are a few tweaks that should be made to the AST while we're making breaking changes:

- [x] `Block.startingRange` - I think we can eliminate this if we instead include whitespace or newlines in the leadingTrivia of the first statement's first token. 
- [x] `IfStatement.isInline` - probably remove? what's the purpose of this? Does it actually matter in the context of syntax validation and transpiling?
- [x] standardize `equal` or `equals` for tokens in statements and expressions
- ~do we need a dedicated `Identifier` token type?~
- [x] for `FunctionType.tokens.end`, should we call it `endFunctionType` instead?
- [x] `ImportStatement.filePath` -> rename to `.path`

**Comment by TwitchBronBron** [comment]
Added another suggestion:

- `ImportStatement.filePath` -> rename to `.path`

**Comment by markwpearce** [comment]
re: `Block.startingRange`

Removing this causes problems with "empty" blocks...

consider:
```
function noop(x)


end function
```

if there are no statements in that block, it effectively has no range, even though in reality there are characters (whitespace, etc), inside it.

Any searches based on range position will not work, because the block has no range, so `util.comparePositionToRange()` will not work.

Any ideas on how to deal with that?

**Comment by TwitchBronBron** [comment]
Can we look at `this.parent.range` to determine our range?

**Comment by markwpearce** [comment]
An *alternate* solution here is to make a giant if statement in the `Block.range` getter:

```
    get range(): Range {
        if (this.statements.length > 0) {
            return util.createBoundingRange(...(this.statements));
        }
        if (isFunctionExpression(this.parent)) {
            const lastBitBefore = util.createBoundingRange(
                this.parent.tokens.functionType,
                this.parent.tokens.leftParen,
                ...this.parent.parameters,
                this.parent.tokens.rightParen,
                this.parent.tokens.as,
                this.parent.returnTypeExpression
            )?.end;
            return util.createRangeFromPositions(lastBitBefore, this.parent.tokens.endFunctionType?.range?.start);
        } else if (isIfStatement(this.parent)) {
            if (this.parent.thenBranch === this) {
                const lastBitBefore = util.createBoundingRange(
                    this.parent.tokens.then,
                    this.parent.condition
                )?.end;
                const firstBitBefore = util.createBoundingRange(
                    this.parent.tokens.else,
                    this.parent.elseBranch,
                    this.parent.tokens.endIf
                )?.start;
                return util.createRangeFromPositions(lastBitBefore, firstBitBefore);
            } else if (this.parent.elseBranch === this) {
                const lastBitBefore = util.createBoundingRange(
                    this.parent.tokens.else
                )?.end;
                const firstBitBefore = util.createBoundingRange(
                    this.parent.tokens.endIf
                )?.start;
                return util.createRangeFromPositions(lastBitBefore, firstBitBefore);
            }
        } else if (isForStatement(this.parent)) {

        } else if (isForEachStatement(this.parent)) {

        }else if (isWhileStatement(this.parent)) {

        }
        return util.createRange(0, 0, 0, 0);
    }
```

**Comment by markwpearce** [comment]
@TwitchBronBron What is the alternative of not using `TokenKind.Identifier` ?

**Comment by TwitchBronBron** [comment]
> @TwitchBronBron What is the alternative of not using `TokenKind.Identifier` ?

I think I was talking about this thing. 

https://github.com/rokucommunity/brighterscript/blob/42db50190171f83dfac6d501a9c797a97fa00d3a/src/lexer/Token.ts#L33

But the more I look at it, it's probably good to be more specific, so let's just ignore that point.

**Comment by markwpearce** [comment]
Great. That means this issue is complete
