### ISSUE TITLE
cannot find namespace in source scope

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1058]
I've got a namespace called `api` declared in `source/`, and then I try to use it from a different namespace also declared in `source/`, and it's not available. 

Steps to reproduce:
- clone [jellyfin-roku](https://github.com/jellyfin/jellyfin-roku)
- install latest brighterscript alpha (1.0.0-alpha.25 at the time of writing this)
- disable plugins in bsconfig.json (because bslint is broken against this version)
- open `source/utils/quickplay.bs` and see all the errors about `api` not being found.

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/0a303248-6652-4453-84c2-8df35b16525e)

**Comment by markwpearce** [comment]
Solved with #1063
