### ISSUE TITLE
How to FormatJson() of BrighterScript object

### ISSUE THREAD

**Issue by vovan888** [rokucommunity/brighterscript#1077]
Consider the following example. Running it results in TestClassJson = "".

```
class TestClass
    public name as string

    public function walk()
        print "walk"
    end function
end class

    TestClassInstance = new TestClass()
    TestClassInstance.name = "TestClassInstance"
    TestClassInstance.walk()
    TestClassJson = FormatJson(TestClassInstance)
```

**Comment by TwitchBronBron** [comment]
When I run your example, I get this error in the console:
![image](https://github.com/rokucommunity/brighterscript/assets/2544493/9e650cf7-fb65-48bf-9850-aaa3e9d91cce)

When I eliminate the methods, then it works. 
```
TestClassInstance = new TestClass()
TestClassInstance.name = "TestClassInstance"
TestClassInstance.walk()
TestClassInstance.walk = invalid
TestClassInstance.new = invalid
TestClassJson = FormatJson(TestClassInstance)
print TestClassJson
````

```bash
{"name":"TestClassInstance","new":null,"walk":null}
```

So the quick answer is to delete all the methods from the classes. 

This might be worth a brighterscript enhancement that adds a `.ToJson()` method to classes that strip out the non-serializable stuff.

**Comment by TwitchBronBron** [comment]
I just discovered an undocumented way of safely stripping out unsupported items. You should be able to do this:

```brighterscript
TestClassInstance = new TestClass()
TestClassInstance.name = "TestClassInstance"
TestClassInstance.walk()
TestClassJson = FormatJson(TestClassInstance, 256) 'flag 256 sets all non-serializable items to to `null`
print TestClassJson
```

**Comment by TwitchBronBron** [comment]
I'm going to close this because it's more a problem with the platform than with brighterscript, and with the `256` flag you _should_ be able to get what you want from it.
