### ISSUE TITLE
Empty interfaces break the parser

### ISSUE THREAD

**Issue by luis-soares-sky** [rokucommunity/brighterscript#1081]
If I declare an empty interface, it breaks the parser. The formatter (which I have on save/paste) also starts acting out.

<img width="424" alt="image" src="https://github.com/rokucommunity/brighterscript/assets/57358121/335f1613-030b-4057-b24c-6dd8060fa3d6">

As soon as I declare something within it, it works fine.

<img width="262" alt="image" src="https://github.com/rokucommunity/brighterscript/assets/57358121/7ee2eaf7-af6e-4481-8dc4-7842983d3190">

**Comment by TwitchBronBron** [comment]
Fixed by #1082.
