### ISSUE TITLE
Improve the "An error has occurred" message for empty `throw` statements

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1086]
Improve the "An error has occurred" message for empty `throw` statements.

user-defined exceptions get assigned e.number as `40`. 

ERR_USER              :  &h28     ' User-specified exception

So maybe the error message could be more like `User-specified exception`

This would be a breaking change, so it should go into v1 before it releases

We decided to use "User-specified exception" because it aligns with the comment in the official Roku error codes file.
![image](https://github.com/rokucommunity/brighterscript/assets/2544493/9abbf16b-7a19-45a6-9ea5-4d3e68358f78)

**Comment by markwpearce** [comment]
Should we be nice and it be something like:

`User-specified exception at PKG_PATH:LINE_NUM`

**Comment by TwitchBronBron** [comment]
@chrisdp this was mostly your concern. What do you think the error message should be?

**Comment by chrisdp** [comment]
I like the default as `User-specified exception`
