### ISSUE TITLE
For each variable missing inferred type 

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1087]
![image](https://github.com/rokucommunity/brighterscript/assets/2544493/63582ddc-070e-4089-98a8-2c6d95e38aba)

**Comment by markwpearce** [comment]
FWIW, inside the for loop, the type IS inferred... it's just at the `for each` line that the type is unknown.
![image](https://github.com/rokucommunity/brighterscript/assets/810290/a2ff7857-9aff-4655-a718-729e25b444f6)

**Comment by markwpearce** [comment]
Also not a problem for regular `for` loop:

![image](https://github.com/rokucommunity/brighterscript/assets/810290/f42319f8-2095-44f9-80e3-30577ef7862d)
