### ISSUE TITLE
Using enums in ternary if statements has unused variable warnings when compiled

### ISSUE THREAD

**Issue by agohof** [rokucommunity/brighterscript#1091]
When using enums to get values in a ternary if statement, the transpiled code will set the enums as params but it won't use them to get the results. Instead, it inserts the actual values directly in the return statements.

### Example

Using the following enums:
```brightscript
enum ThumbButtonSize
    Width = 40
    Height = 37
end enum

enum ClosedCaptionsButtonSize
    Width = 38
    Height = 30
end enum
```

This ternary operation:
```brightscript
buttonBaseWidth = (nodeId = "closedCaptions") ? ClosedCaptionsButtonSize.Width : ThumbButtonSize.Width
```

Will be transpiled into the following code:
```brightscript
buttonBaseWidth = (function(__bsCondition, ClosedCaptionsButtonSize, ThumbButtonSize)
            if __bsCondition then
                return 38
            else
                return 40
            end if
        end function)((nodeId = "closedCaptions"), ClosedCaptionsButtonSize, ThumbButtonSize)
```

When compiled, there will be unused variable warnings because of the `ClosedCaptionsButtonSize` and `ThumbButtonSize` params.

**Comment by TwitchBronBron** [comment]
Yeah, we need to improve the transpiled output to exclude those enums. Good catch.

**Comment by TwitchBronBron** [comment]
Any chance you'd be interested in trying to fix this? I think `util.getExpressionInfo()` needs updated to exclude enums, constants, and interfaces.

https://github.com/rokucommunity/brighterscript/blob/aa92cecad83ce852a6934b0397f6efde6ba941f0/src/parser/Expression.ts#L1381

https://github.com/rokucommunity/brighterscript/blob/aa92cecad83ce852a6934b0397f6efde6ba941f0/src/util.ts#L1189-L1214
