### ISSUE TITLE
Rename brs-specific types to be prefixed with `brs`

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1100]
Since the file api has landed, we'll eventually start adding more parsers for things like `manifest`, `.json` files, `.ts` translation fles ,etc. 

We should rename the brs parser class names and interfaces so they relate specifically to brs. Some examples:
 - `Token` -> `BrsToken`
 - `TokenKind` -> `BrsTokenKind` 

I'm sure there are more. I'm open to discussions about whether this should actually be implemented, but it feels like we should.

**Comment by markwpearce** [comment]
My opinion - this is not needed. This is Brighterscript (say it like King Leonidas) .. most stuff in it is BRS specific, if we start dealing with other stuff (XML, Manifests, etc.) let them have their own names, but Parser, Token, Lexer, etc. are the core, and it's okay to leave off the Brs...

**Comment by TwitchBronBron** [comment]
Yeah, I think you're right. Closing
