### ISSUE TITLE
type mismatch for anonymous AA and interface

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1102]
Returning an AA literal with a nested AA that conforms to an interface is being incorrectly flagged as a type mismatch. 

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/a72b812c-4330-462c-8598-6490db09b2a6)

Here's the source code.
```
namespace alpha.beta

    interface Stream
        thumbnailTiler as Thumbnail
    end interface

    interface Thumbnail
        count as integer
    end interface

    function createStreamObject() as Stream
        return {
            thumbnailTiler: {
                count: 1
            }
        }
    end function
end namespace

```

**Comment by markwpearce** [comment]
this is only because the `count` property is being overridden.

**Comment by TwitchBronBron** [comment]
It's still a bug, right? We should be able to override the `.count` property?
