### ISSUE TITLE
Reduce file looping during scope validation

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1108]
#1105 moved all scope validation into BscPlugin. However, it was then noticed that there are two separate loops iterating over files in that PR (see [this](https://github.com/rokucommunity/brighterscript/pull/1105#discussion_r1520354047) comment). 

We should optimize the validators to do a single loop instead of multiple.

**Comment by markwpearce** [comment]
potentially not an issue anymore after #1123
