### ISSUE TITLE
Add comments to the AST walker

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1128]
Now that we removed `CommentStatement` from the AST as nodes, we need a way to discover all comments when walking the AST. 

Maybe a new WalkMode option that includes comments?

**Comment by markwpearce** [comment]
Goal for usage:

```
file.ast.walk(createVisitor({
   CommentToken: (comment) -> {
       // this is a comment!
       
   }),
   { walkMode: WalkMode.visitAllRecursive & WalkMode.VisitComments }
);
```
