### ISSUE TITLE
accessing roassociative array using as roAssociativeArray is not supported  in v1.0.0-alpha29 

### ISSUE THREAD

**Issue by rdaci23** [rokucommunity/brighterscript#1129]
if not (m as roAssociativeArray).doesExist(fieldName) logs unknown expression 
![image](https://github.com/rokucommunity/brighterscript/assets/6873131/ed9f23fb-7f61-457c-a9dc-1ec6687494d1)

**Comment by markwpearce** [comment]
fixed with #1143
