### ISSUE TITLE
bogus method overriding warning, when file included in component that is extended

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#113]
This is easy to see in the open source MList project.

Compilation reports a ton of these warnings:

```
../../../../../tmp/buildTmp/source/rLog/rLogMixin.bs:84:10 - hint BS1010: Function 'logWarn' included in 'components/maestro/view/core/BaseScreen.xml' overrides function in 'source/rLog/rLogMixin.bs' included in 'components/maestro/view/core/BaseView.xml'.

 84  function logWarn(message, value = "#RLN#", value2 = "#RLN#", value3 = "#RLN#", value4 = "#RLN#", value5 = "#RLN#", value6 = "#RLN#", value7 = "#RLN#", value8 = "#RLN#", value9 = "#RLN#") as void
 84           ~~~~~~~                            
```

BaseScreen extends BaseView, which imports rLogMixin. the function is not redefined; BaseScreen does not import rLogMixin; but imports FocusMixin which does.

In any case, the compiler is wrong here, and even if one of BaseScreen's imports, imports rLogMixin, it should know it's already imported in BaseView, and not throw these warnings.

**Comment by elsassph** [comment]
Any solution to that? I've added a `diagnosticFilter` for now:
```
    diagnosticFilters: [{
        'src': '**/*',
        'codes': [1010] // ignore override error
    }]
```
