### ISSUE TITLE
cannot access protected members in v1.0.0-alpha29

### ISSUE THREAD

**Issue by rdaci23** [rokucommunity/brighterscript#1130]
Cannot access protected member from subclasses
![image](https://github.com/rokucommunity/brighterscript/assets/6873131/9ed313a3-aca9-4fc4-81e2-5ee756210514)
![image](https://github.com/rokucommunity/brighterscript/assets/6873131/b7637105-3d6c-4aed-9bb8-6e87c02c2f4d)

**Comment by markwpearce** [comment]
@rdaci23 I can't reproduce this issue.

This works for me in 1.0.0.alpha.29 ... If you can get a concise example of failure, please let me know.


```
namespace alpha
  class SuperKlass

    node as roSGNode
    protected name as string

    sub new(node as roSGNode)
      m.name = node.id
    end sub

    function getValue()
      return "Hello!"
    end function

  end class
end namespace

class SubKlass extends alpha.SuperKlass

  node as roSGNodeLabel

  sub new()
    super(createObject("roSGNode", "Label"))
  end sub

  sub setText(newText as string)
    m.node.text = newText + m.name
    print m.getValue()
    print super.getValue()
  end sub
end class
```

**Comment by rdaci23** [comment]
@markwpearce I think it was something with my vscode, I just update it to the latest version and I can't reproduce it either now. Closing this issue for now.

**Comment by rdaci23** [comment]
@markwpearce this is how I reproduce the issue
![Screenshot 2024-04-24 at 12 50 22](https://github.com/rokucommunity/brighterscript/assets/6873131/d45975fc-0a08-476a-a059-f2ff765309a5)
![Screenshot 2024-04-24 at 12 51 55](https://github.com/rokucommunity/brighterscript/assets/6873131/81414d09-dab2-408e-ade1-e056dd110db1)
