### ISSUE TITLE
Remove `.file` prop from `BsDiagnostic`

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1155]
When #1136 lands, we should consider removing `file` from the `BsDiagnostic` interface. It doesn't feel right being attached to a diagnostic, and we could easily update `DiagnosticsManager` to support returning a new object that includes the scope/file information (i.e. the file) for a diagnostic) if we need that information.

This would be a breaking change, so likely should be done as part of v1.

**Comment by markwpearce** [comment]
Not really sure how this works. How do we associate with a diagnostic with a file? Do we use the `Location` property on the `Diagnostic.relatedInformation`?

**Comment by TwitchBronBron** [comment]
All diagnostics flow through the diagnosticManager now. So `file` would be a required property when registering a diagnostic. Something like this:

```ts
program.diagnostics.register({
    ...DiagnosticMessages.cannotFindName('someVar'),
}, {
    file: theFile,
});
```

Then if we need to know what file that diagnostic comes from, that would be an attribute of the return value from the diagnostic manager. Perhaps something like this?:

```ts
diagnosticManager.getDiagnosticsByFile(); // Map<BscFile, Diagnostic[]>; 
```

**Comment by markwpearce** [comment]
We decided that we should replace `.file` and `.range` with `.location` to mirror the changes in the AST Nodes.
