### ISSUE TITLE
alias statement gets stuck and won't validate again

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1164]
https://github.com/rokucommunity/brighterscript/assets/2544493/c3ddd158-b0d1-44b5-8f64-1fa9add498bf

**Comment by markwpearce** [comment]
I can't reproduce this...

**Comment by TwitchBronBron** [comment]
Did you test in the validate-single-scope branch? Perhaps it got fixed with some of your recent changes?

**Comment by markwpearce** [comment]
Ahh.. yeah.. I see. 
I'll fix it in the `validate_single_scope` branch
