### ISSUE TITLE
absolutely off the charts insane static type checking on everything

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#12]
we could perhaps/maybe/theoretically create a shadow project, in typescript, with types that match the brightscript project's types, and use that to ascertain all of our type/scope errors.. 

point being, use typescripts type inference as a proxy, rather than having to write it all for brighterscript.

**Comment by TwitchBronBron** [comment]
I'm closing this because I think we have a viable product that works.
