### ISSUE TITLE
Missing `true`, `false`, and `invalid` in completion results

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1203]
https://github.com/RokuCommunity/brighterscript/pull/1009 added completion results for  `true`, `false`, and `invalid`. But when I test this against v1.0.0-alpha.30, they don't seem to be showing up?

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/e6df2a07-4bb1-46c7-9c5d-a3b1c7ebf1ba)

**Comment by markwpearce** [comment]
Are you sure this is still happening? I get those values in the completions …

**Comment by TwitchBronBron** [comment]
This seems to be working properly now. Not sure what changed, but all good! 😄
