### ISSUE TITLE
How do plugins add/remove comments in v1?

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1206]
Some of the `getLeadingTrivia()` and `getTrailingTrivia()` calls return a _new_ array of trivia, which means plugins don't have an easy way to manipulate that list without digging around in the leadingTrivia of each statement (or child expression). For example, a plugin that wants to prepend a comment to the start of every function, or delete all leading comments for a given statement. 

How should we handle something like this with the plugin system and the new v1 comments-as-trivia model?

**Comment by markwpearce** [comment]
Could we just have a method on all nodes… something like:

`prependLeadingTrivia(trivia: Array<CommentToken | WhitespaceToken l NewLineToken>)`

maybe also `append…`
