### ISSUE TITLE
A call to 'super()' must be the first statement in this constructor method. - reported falsely

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#121]
![image](https://user-images.githubusercontent.com/1214545/85476783-a1022300-b57e-11ea-9bcd-509fb0be567c.png)

seems related to the prior field declaration; only occurs when navigating to a file. disappears if I remove and replace the line.

**Comment by TwitchBronBron** [comment]
@georgejecook do you still see this issue sometimes? If so, can you provide some reproducible steps?

**Comment by georgejecook** [comment]
not seen in forever.
