### ISSUE TITLE
certain imports do not produce a script tag when importing

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#122]
I have this import in several files:

```
import "pkg:/source/maestro/ioc/IOCMixin.bs"
```

it's a valid import, imported into `BaseClass.bs`, extended by `AuthManager.bs`

The `AuthenticationService` xml imports `AuthManager.bs`

I would expect the import to be present in the build `AuthenticationService.xml`'s script imports: it is not
I add the import to the extended `AuthManager` class; it still doesn't show up.
I add it to the `AuthenticationService.bs` file, it still doesn't show up as a script tag

The only recourse I have is to add the imports that get dropped as a script tag in the file.

**Comment by georgejecook** [comment]
I've looked into this more; but I can't see rhyme or reason to it - my only guess is perhaps we're missing an error somewhere.. I'll try and investigate some more

**Comment by TwitchBronBron** [comment]
Yeah very strange. Can you put together a very small sample project that will reproduce the issue? Then I can dig into this early next week.

**Comment by TwitchBronBron** [comment]
I think this spec accurately reproduces the problem and it fails, which seems to validate that this is a bug. @georgejecook does this look correct in terms of how the files reference each other?

```
it('complicated import graph adds correct script tags', async () => {
    await program.addOrReplaceFile('source/maestro/ioc/IOCMixin.bs', `
        sub DoIocThings()
        end sub
    `);
    await program.addOrReplaceFile('source/BaseClass.bs', `
        import "pkg:/source/maestro/ioc/IOCMixin.bs"
    `);

    await program.addOrReplaceFile('components/AuthManager.bs', `
        import "source/BaseClass.bs"
    `);
    await testTranspile(`
        <?xml version="1.0" encoding="utf-8" ?>
        <component name="ChildScene" extends="ParentScene">
            <script type="text/brighterscript" uri="AuthManager.bs" />
        </component>
    `, `
        <?xml version="1.0" encoding="utf-8" ?>
        <component name="ChildScene" extends="ParentScene">
            <script type="text/brightscript" uri="AuthManager.brs" />
            <script type="text/brightscript" uri="pkg:/source/maestro/ioc/IOCMixin.bs" />
            <script type="text/brightscript" uri="pkg:/source/BaseClass.brs" />
            <script type="text/brightscript" uri="pkg:/source/bslib.brs" />
        </component>
    `, null, 'components/AuthenticationService.xml');
});
```

**Comment by georgejecook** [comment]
I'm closing this, as it appears to be working on 2 projects these days.
