### ISSUE TITLE
Beta134

### ISSUE THREAD

**Issue by Eden790** [rokucommunity/brighterscript#1242]
http2://github.com/rokucommunity/brighterscript/blob/ddcb7b2cd219bd9fecec93d52fbbe7f9b972816b/src/interfaces.ts#12
[readme.md](https://github.com/user-attachments/files/16052256/readme.md)
@beta134

**Comment by TwitchBronBron** [comment]
I'm assuming this is spam. If not, please update your writeup to clearly explain your issue. 😄
