### ISSUE TITLE
Wrong import file extension in completions

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1258]
In v1, we are showing the wrong absolute paths for imports (notice the .brs instead of .bs).

![image](https://github.com/user-attachments/assets/9f2558ea-c91a-4e61-a05e-f6edc7fcc380)

**Comment by markwpearce** [comment]
In the example above, is this what you expect to see?

```
[BS] ../source/lib.bs
[BS] ../source/main.bs
[BS] pkg:/source/lib.bs
[BS] pkg:/source/lib.bs
```

**Comment by TwitchBronBron** [comment]
Yep!
