### ISSUE TITLE
cli trying to make folders at root

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#127]
For certain users (most likely linux/mac users), the cli seems to want  to write directly to the root of the file system, instead of relative to cwd. 

> 
> [10:37:08un44fin44 PM] Parsing files
> [10:37:08un44fin44 PM] Validating project
> [10:37:08un44fin44 PM] Copying to staging directory
> [10:37:08un44fin44 PM] Transpiling
> { [Error: EROFS: read-only file system, mkdir '/source'] errno: -30, code: 'EROFS', syscall: 'mkdir', path: '/source' }
> error Command failed with exit code 1.

**Comment by elsassph** [comment]
This is what #130 fixes

**Comment by TwitchBronBron** [comment]
Right. Thanks!
