### ISSUE TITLE
Merge `ExitWhileStatement` and `ExitForStatement`

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1285]
I'm not sure why there are two separate statements here, for `exit while` and `exit for`. I think `exit` on its own is also _technically_ valid syntax.

We should merge them into a single `ExitStatement` that optionally takes a tokenKind for the thing that comes after it.

**Comment by markwpearce** [comment]
`exit` on its own is a syntax error:

```
  for i = 1 to 10
    if i mod 4 = 0
      exit
    end if
    print i
  end for
```

produces:

```
Syntax Error. (compile error &h02 (ERR_SYNTAX): syntax error ) in main.main(12)
=================================================================
An error occurred while attempting to compile the application's components:
-------> Compilation Failed.
pkg:/source/main.brs(NaN)
Syntax Error. (compile error &h02 (ERR_SYNTAX): syntax error ) in main.main(12)
```

**Comment by TwitchBronBron** [comment]
Regardless of the standalone `exit` not being valid, is there any reason to have separate `exit for` and `exit while` statements? We have a single `ContinueStatement`, I think `exit <something>` makes sense to be a single statement type as well.

https://github.com/rokucommunity/brighterscript/blob/353f4638c8a8eed7aa003b1db0438a84e4cbc560/src/parser/Statement.ts#L3601

**Comment by markwpearce** [comment]
Good point... i'll merge them
