### ISSUE TITLE
CLI crash on Mac

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/brighterscript#129]
I've picked a random Roku sample, which works nicely in VSCode and is following the default organisation, but I can't get it to work as `.bs` (on Mac):

- command line `bsc` (no `bsconfig.json`) fails with some `[Error: EACCES: permission denied, mkdir '/source']`, which possibly means some config defaults don't work,
- VSCode "Debug" doesn't automatically transpile; did I miss maybe an argument in the launch configuration?

**Comment by TwitchBronBron** [comment]
I was just made aware of a yesterday relating to the back command line not working on certain operating systems. To get around this for now, try specifying outDir and stagingFolderPath...for some reason that fixes it for some people. This is on my list to fix early next week. 

And no, the extension does not yet currently transpile brighterscript, that's on the road map.

**Comment by elsassph** [comment]
Ok, can confirm that setting `"stagingFolderPath": "out/staging"` solves the CLI issue on Mac at least.

**Comment by TwitchBronBron** [comment]
This has been fixed in [v0.10.11](https://github.com/rokucommunity/brighterscript/releases/tag/v0.10.11)
