### ISSUE TITLE
Chat?

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/brighterscript#132]
Is there a brighterscript team discussion place, like gitter for instance?
I'm doing some debugging and have lots of questions :D (like why is `sgn` declared twice in the globals?)

**Comment by TwitchBronBron** [comment]
Yeah, there is. We use slack. There's a whole Roku community there. Here's the link:

https://join.slack.com/t/rokudevelopers/shared_invite/zt-4vw7rg6v-NH46oY7hTktpRIBM_zGvwA

For this project, we are in the #brighterscript channel. But I'd also recommend joining the #vscode-bs-lang-ext channel.
