### ISSUE TITLE
unnecessaryCodebehindScriptImport should be a bslint diagnostic

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#1363]
Move this diagnostic into bslint, it's a code style diagnostic and shouldn't be showing up in bsc.

    unnecessaryCodebehindScriptImport: () => ({
        message: `This import is unnecessary because compiler option 'autoImportComponentScript' is enabled`,
        legacyCode: 1107,
        severity: DiagnosticSeverity.Warning,
        code: 'unnecessary-import'
    }),

**Comment by markwpearce** [comment]
Duplicate of #1329
