### ISSUE TITLE
add mechanism to replace node.callfunc("foo", with node.foo syntax

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#14]
It'd be wonderful to not have to use callfunc anymore

given a node with function foo, I want to be able to do 
node.foo, instead of node.callFunc("foo"

I also want to be able to call it like a regular function without having to pass a single args param, i.e.

node.foo(title, video, someOtherThing)

as opposed to node.callFunc("foo", {title:title, video:video, someOtherThing"..etc)

an idea to achieve this, without having to need full-bulletproof type checking implemented is something like this
1. all `.bs` defined functions that map to an xml file's node's public interface functions result in the creation of a new function (e.g. foo_public) and the xml interface's definition will use that for function calls - the code for that destructures args to the fieldnames in the real method signature, and invokes that method
2. all callfuncs are replaced with BS_callFunc(node, arg1, arg2, arg3)
3. that will bundle the args up and pass them into node.callfunc

**Comment by triwav** [comment]
Makes sense. One feature I love in Swift (a carryover from Objective-c is named params) https://useyourloaf.com/blog/swift-named-parameters/. It's a long shot but thought I'd throw it out there. Could either have the call site pass in an array if not using named params which then translates to the function count or an AA which then figures out the correct order to pass the params in based on the ordering of the names

**Comment by TwitchBronBron** [comment]
@georgejecook can you confirm that this issue can be closed now that we have the callfunc operator introduced in [v0.10.0](https://github.com/rokucommunity/brighterscript/compare/v0.9.8...v0.10.0)?
