### ISSUE TITLE
let us progressively compile, to reduce compile times

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#141]
Following on from our conversation, I will implement a mechanism in ProgramBuilder to indicate it will be in a progressive compilation watch mode.

This means it will not rebuild every single time a file changes; instead storing up all of the changes, until `flush` is called, at which point it will update.

Also, the ProgramBuilder will optionally communicate with other processes with files acting as semaphores, so it can be left running in it's own process, and work in concert with a build process (such as gulp, triggered by the ide). This mechanism will work as follows.

- The ProgramBuilder will watch for a file named `/tmp/.bsc-program-builder-status`.
- if Updated with the text "build-now", the ProgramBuilder will update the file `/tmp/.bsc-program-builder-status` with the text `building`, as an ack to observing processes, and run flush
- when the flush is completed,  the ProgramBuilder will update the file `/tmp/.bsc-program-builder-status` with the text `waiting`

Additionally, I will implement a function named `runContinuousBuild` (or similar), which will:
 - write "build-now" to `/tmp/.bsc-program-builder-status
 - wait 5 seconds for `/tmp/.bsc-program-builder-status` to change to "building"
 - if not changed, will report an error with instructions on how to run the program progressive compilation mode
 - if changed, will wait on the `/tmp/.bsc-program-builder-status` to change to "waiting", at which point we know the continuous build is working.

This will allow us to run the program builder in one instance, and communicate with it from our build tools. We can later improve  on the underpinning mechanism, or move it out to the LSP, once we have a better idea of people's tool chains, and what problems we need to address.

**Comment by elsassph** [comment]
Wouldn't it be simpler to have a configurable "quiet" period for the watcher?

**Comment by georgejecook** [comment]
@chrisdp has informed this is a moot point now, coz we're all using plugins, and can run in watcher mode.

**Comment by elsassph** [comment]
Build is also much faster than it was at this time?

**Comment by georgejecook** [comment]
Indeed

>
