### ISSUE TITLE
Support directory imports

### ISSUE THREAD

**Issue by iObject** [rokucommunity/brighterscript#161]
Add support to import all .bs files in a directory

**Something like:**
`
import "./myDependencies/*"
`

**Comment by TwitchBronBron** [comment]
I'm not sure that's something we want to support. In the near-future, we will be adding import hints which should help automate importing missing files. Alternatively, you could easily create a "bucket" of imports for `myDependencies` folder and import that. For example:

```BrighterScript
'myDependencies/index.bs
import "./File.bs"
import "./File2.bs"
import "./File3.bs"
```

```BrighterScript
'main.bs
import "./myDependencies/index.bs"
```

**Comment by TwitchBronBron** [comment]
I appreciate the suggestion, but I don't think this is something we want to support at this time. It would require the language server regularly polling the directory for dependencies, and makes things less explicit. I'd much rather just continue to support the "bucket" suggestion from before.
