### ISSUE TITLE
placing an EmptyStatement can cause transpilation to crash in some scenarios

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#195]
If modifying code to change some statements to `EmptyStatement` immediately before a comment, like this:

```
 m.logError() ' <<< change this to EMptyStatement in a plugin
    ' if (type(Rooibos__Init) = "Function") then Rooibos__Init(invalid, invalid, invalid, m)
    InitScreen()
```

then the transpiler will crash in linesTouch in `util.ts`, when the EmptyStatement get's passed in from `Block.transpile` method.

**Comment by TwitchBronBron** [comment]
I fixed this in the brs-plugin branch, it'll be fixed when that lands.
