### ISSUE TITLE
Namespace specification

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#2]
This is a proposal for namespaces. 

# Syntax
```VB
'simple
namespace App
    function GetSettings()

    end function
end namespace

'multi-part
namespace App.UI.Screens
    function MainScreen()
    end function
end namespace

'nested
namespace App
    namespace Util
        namespace Functions
            function GetSomething()
            end function
        end namespace
    end namespace
end namespace
```

# Output
```brightscript
function App_GetSettings()
end function

function App_UI_Screens_MainScreen()
end function

function App_Util_Functions_GetSomething()
end function
```

#Usage
## BrighterScript
```VB
sub main()
    App.GetSettings()
    App.UI.Screens.MainScreen()
    App.Util.Functions.GetSomething()
end sub
```

## BrightScript
```brightscript
sub main()
    App_GetSettings()
    App_UI_Screens_MainScreen()
    App_Util_Functions_GetSomething()
end sub
```

**Comment by georgejecook** [comment]
This is way nicer than what I've already done..

Does it fail on namespace collisions?

How does mapping work? i.e getting it line for line with the ide - are you going to support source maps?

**Comment by georgejecook** [comment]
I would also like to be able to specify a namespace for a whole file, without having to wrap with end namespace

i.e. iif I do 
```
Namespace App
```

before the rest of my code, then the entire file should be namespaced to App - this is how I would use this language feature - I wouldn't want to faff around with the start/end namespace syntax, as files are always conceptually distinct scopes in all of my code.

**Comment by TwitchBronBron** [comment]
I plan on eventually supporting source maps...although not right away because generating those is still magic to me. :D 

As far as the namespace thing, I don't think it's worth having the shorthand namespace only-at-the-top style. That adds unnecessary complexity to the parsing. What you're asking for is similar to java packages...but what I'm proposing is more like C# namespaces. We need to pick one direction or the other. I personally prefer the C# style namespaces, and as such, it should always have an open and close.

**Comment by TwitchBronBron** [comment]
With java packages, you can only indicate a package for a single file, at the top, and that's it. ([The package keyword, if it appears, must be the first token of Java code](https://docstore.mik.ua/orelly/java-ent/jnut/ch02_11.htm))With C#, you can have multiple namespaces nested, etc. It's much more flexible.

**Comment by georgejecook** [comment]
Yes - agreed. Was as a bad suggestion to save me time with converting my previous namespace design.

**Comment by TwitchBronBron** [comment]
This has been completed.
