### ISSUE TITLE
super calls are wrongly subjected to missing callToUnknownFunction diagnostics

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#202]
all super calls in my project result in this erroneous diagnostic.

I'm guessing super is a keyword in this context; but I don't know the references code well enough to know if it should be there or not.
In any case, I workaround for the time being by adding this code:
![image](https://user-images.githubusercontent.com/1214545/95666400-c19abc80-0b1e-11eb-952f-7c232470f377.png)

**Comment by TwitchBronBron** [comment]
With the current validation logic, there is no way to identify which function calls are found within a class method. So in the short-term, I'm going to implement your suggested fix. Long-term, the validation logic will be refactored to have better visibility across the AST so we can better handle these situations.
