### ISSUE TITLE
@. callfunc shorthand results in wrong cannot find function name diagnostic

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#205]
this .bs code:
```
      childRail@.initializeWithRiversJson(childRail.riversJson)
```
reports diagnostic : brs1001 - `Cannot find function with name 'childRail' when this file is included in scope 'source'`
transpilation still succeeds, as this screenshot shows.

![image](https://user-images.githubusercontent.com/1214545/95692376-e3617580-0bea-11eb-91e0-4c9caa96fc1e.png)

I've had a look at the code; but not sure how best to deal with this to workaround it.. not sure if it should even be in the `functionExpressions`  references, as it's a callfun expression, or if it should just get filtered out of the response from `findFunctionCalls`

**Comment by TwitchBronBron** [comment]
Just a clarification: `functionExpressions` is a list of functions, not function calls, so the statement "not sure if it should even be in the functionExpressions references" doesn't make much sense. 

However, you are correct, CallfuncExpressions should be excluded from the parser's `callExpressions` list (the results of `findFunctionCalls`). Good find.
