### ISSUE TITLE
get multiple completions depending on number of workspaces

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#207]
this code from LanguageServer.ts incorrectly returns hasFile as true, for files that do not exist in that workspace, causing all completions to multiple times the number of workspaces.

![image](https://user-images.githubusercontent.com/1214545/95695528-f54c1400-0bfc-11eb-9cbd-d2bcbf108d6a.png)

it seems the issue is the server is assigning the same builder to all workspaces, my second workspace is just a folder of json files; it's not even a brs project, yet it has _all the same files as my main project_

**Comment by TwitchBronBron** [comment]
I'm unbale to reproduce this in my unit test suite. Here's the test I wrote:
![image](https://user-images.githubusercontent.com/2544493/95698447-f76b9e00-0c0f-11eb-95ad-78241b689d25.png)

You can run the test from this branch: https://github.com/rokucommunity/brighterscript/tree/multi-workspace-duplicate-completions

I have a feeling this is something specific to your project setup.

**Comment by TwitchBronBron** [comment]
Thanks for the screen share session, that really helped. The problem is that, in a multi-workspace situation, `cwd` should be the workspaceFolder, but we weren't passing the proper `cwd`. 
![image](https://user-images.githubusercontent.com/2544493/95938076-1fd9d080-0da7-11eb-8180-d50c7ac8b122.png)
