### ISSUE TITLE
Try catch keyword support

### ISSUE THREAD

**Issue by hornyhedgehog** [rokucommunity/brighterscript#218]
Please add try catch block support which releases in 9.4fw
Usually looks in next way:
`SUB main()
    x = 1
    try
        PRINT x.foo
    catch e
        PRINT e.number,e.message
    end try
END SUB
`

**Comment by TwitchBronBron** [comment]
yes, we definitely want to support this! There are few large items on my plate right now so I could probably get to this sometime next month. pull requests are always welcome if you're looking to see syntax support arrive sooner. :)
