### ISSUE TITLE
Parsing of exponential form failed

### ISSUE THREAD

**Issue by TrevorSundberg** [rokucommunity/brighterscript#231]
If I have this line:
```
x = 2.3659475627512424e-38
```
Brighterscript fails to parse it and prints:
```
error BS1047: Expected newline or ':' after assignment
```
And highlights under the `e` exponent on the `e-38`

**Comment by TwitchBronBron** [comment]
This is interesting. So at runtime, BrightScript will treat this value as a single-precision float.
```BrightScript
x = 2.3659475627512424e-38
print type(x); x 
'> Float 2.36595e-38
```

Removing the exponent causes this number to be a double

```BrightScript
x = 2.3659475627512424
print type(x); x
'> Double 2.3659475627512 
```
Adding the double type declaration char makes it a double

```BrightScript
x = 2.3659475627512424e-38#
print type(x); x
'> Double 2.3659475627512e-38 
```

Anyway, there's definitely a lexer bug, and we'll get it fixed. Just found it interesting that it wouldn't automatically treat such a large exponential number as a double.

**Comment by TrevorSundberg** [comment]
@TwitchBronBron Thanks for running those tests! The reason I was filing these bugs is I've created the project https://github.com/TrevorSundberg/wasm2brs that converts WebAssembly into BrightScript, which means you can compile C/C++/Rust into BrightScript. We even got DOOM running on the Roku using wasm2brs. I'd love to use BrighterScript as a way of running our tests locally and on a build server, however I've run into a few differences with the parsing as well as the runtime, two of which you just fixed, so thank you!

The wasm2brs project integrates WebAssembly's testsuite which has over 10,000 tests. Currently all of these are passing via BrightScript on an actual Roku device, and I think it would be beneficial to work together on making brighterscript pass these tests too. Let me know what you think :)

**Comment by TwitchBronBron** [comment]
I want the BrighterScript parser to be as close as possible to the on-device Roku (with the new BrighterScript syntax excluded, of course). So yes, I'm definitely open to working together to get brighterscript to pass those tests! 

> I've run into a few differences with the parsing as well as the runtime, two of which you just fixed, so thank you!

Just to be clear, BrighterScript doesn't have a runtime, but the [brs](https://github.com/sjbarag/brs) project does. Our parser was originally based on the `brs` parser, but we have deviated quite significantly from that parser at this point.
