### ISSUE TITLE
Unexpected character '%' (char code 37)

### ISSUE THREAD

**Issue by TrevorSundberg** [rokucommunity/brighterscript#233]
When writing any integer literal such as `0%` the error `Unexpected character '%' (char code 37)` occurs

**Comment by luis-soares-sky** [comment]
I'm somehow seeing this happen with bsc-0.41.5...

![image](https://user-images.githubusercontent.com/57358121/147478562-5a461a21-f203-4f57-a9c2-3eb2d3446e12.png)
