### ISSUE TITLE
docs wrong regarding ElseIf

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#261]
docs incorrectly claim that there is a new ElseIfStatment, when infact else if's are now interpreted as nested ElseBranches.

**Comment by TwitchBronBron** [comment]
Where in the docs? Can you give a link?

**Comment by elsassph** [comment]
Changelog you mean?

**Comment by georgejecook** [comment]
yes. I meant changelog. Can close this then, as that's not really something that will/needs fixing.
