### ISSUE TITLE
Can we please have support for meta.decorator in the grammar?

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#273]
I love annotations and updated rooibos and maestro frameworks to beoth use them; but I can't stand the colors. I'd like to be able to change them to be more like c# where they stand out more. perusing test files in rooibos is just sheer misery for me, as it stands. :(

**Comment by TwitchBronBron** [comment]
Done. This was included in release v0.28.0. Here's an example (hot-pink is all the rage these days. :P ): 

![image](https://user-images.githubusercontent.com/2544493/104830539-223c4280-584e-11eb-9c78-980ad6fb4dc6.png)
