### ISSUE TITLE
crash when transpiling, due to non safe access of item

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#275]
I tried to write a test to isolate this; but I can't get it to reproduce. it might be coz I manipulate the ast, or becuase I have virtual clases I add through a plugin. 

in any case - this is the fix - the `?.` is what I add to prevent the crash.

![image](https://user-images.githubusercontent.com/1214545/104896801-e43b3d80-5977-11eb-847d-ae51f9a42373.png)

We should guard the access to `item` as we in the method below this - because parent class well and could be null

**Comment by TwitchBronBron** [comment]
@georgejecook I believe I fixed this in a recent release. Is this still an issue?

**Comment by georgejecook** [comment]
not seen it since.
