### ISSUE TITLE
writing annotations then functions causes the parser to get stuck forever

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#290]
Apologies that I do not have a unit test for this; but so far the only way I can reproduce it is while typing in the extension.
I've got a gif. note how the symbols disappear - there are lots of errors from the language server for index errors; but I don't think these are the cause; coz I try/catch these and return valid values on my local branch and it still does it; plus (if the LSP responds to pausing) the program cursor is _always_ in the parser.

![annotationbug](https://user-images.githubusercontent.com/1214545/105874224-a3d56280-5ffc-11eb-8412-90a9e3b18a51.gif)

**Comment by TwitchBronBron** [comment]
This was fixed in #291
