### ISSUE TITLE
Import specification

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#3]
# Justification
It can get very difficult sometimes to keep track of what files depend on one another. Many other programming languages have the concept of imports, and this specification brings that concept to brighterscript.

# Syntax
```typescript
import "pkg:/source/lib.brs"
import "../lib.brs"
import "lib.brs"
```

# Output
For source scope (i.e. `pkg:/source` and everything below), an import statement will cause that file to be included in `pkg:/source` folder during packaging. 

For component scope, any component that references a script that has imports, those imports will be added to the component's script imports. For example, consider these source files:

 - `src/components/MyComponent.xml`
     ```xml
   <?xml version="1.0" encoding="utf-8" ?>
   <component name="MyComponent" extends="Scene">
      <script type="text/brightscript" uri="MyComponent.brs" />
   </component>
    ```
 - `src/components/MyComponent.brs`
    ```VB
    import "pkg:/source/lib.brs"
    function DoSomething()
    end function
    ```
    
This will result in the output files as such:
 - `pkg:/components/MyComponent.xml`
     ```xml
   <?xml version="1.0" encoding="utf-8" ?>
   <component name="MyComponent" extends="Scene">
      <script type="text/brightscript" uri="MyComponent.brs" />
      <script type="text/brightscript" uri="pkg:/source/lib.brs" />
   </component>
    ```
 - `pkg:/components/MyComponent.brs`
    ```VB
    function DoSomething()
    end function
    ```

**Comment by georgejecook** [comment]
@TwitchBronBron  got some suggestions (seeing as I just coded this up a cpl of weeks ago):

- Should fail for missing imports
- Should fail gracefully for cyclical imports, with clear error message
- Should _not_ import anything imported by parent scope
- imo - should put imports at end of file - so that the xml files match what was in the IDE as closely as possible

**Comment by TwitchBronBron** [comment]
@georgejecook 

I like 1 and 2 for sure! 
3 might be a little more tricky to implement, but I think I agree with that as well. 

For your 4th point, do you mean the .brs files should have the imports at the end? If so, I don't think I like that. I definitely prefer to have the imports at the TOP of the file, because that very clearly states what this file depends on.

**Comment by georgejecook** [comment]
3. if you need inspiration: https://github.com/georgejecook/brsxmlc/blob/master/src/lib/ImportProcessor.ts

4. No - I mean xml file - at top of brs file is without saying
At top of xml file so that the code in the xml file isn't all offset by numScriptTags lines

**Comment by chrisdp** [comment]
Would the intention also be that this support scripts importing depend scripts?

**Comment by georgejecook** [comment]
yes - that's exactly what it should do, and what my impl referenced above does.

**Comment by TwitchBronBron** [comment]
this has been completed.
