### ISSUE TITLE
log links can print wrong function names in output

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#313]
when the output is pretty printed, it's possible to get the wrong functioname.

![image](https://user-images.githubusercontent.com/1214545/107926097-8ea58100-6f75-11eb-9b48-ab42fda35921.png)

**Comment by elsassph** [comment]
Is that a brighterscript feature?

**Comment by georgejecook** [comment]
oooooh! thanks mate. wrong repo. sorry!
