### ISSUE TITLE
template strings no longer transpile correctly

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#326]
![image](https://user-images.githubusercontent.com/1214545/108592348-bd549a80-736d-11eb-9e78-01de5164d027.png)

breaks everything everywhere for me.

**Comment by georgejecook** [comment]
I don't see how this was an issue before; coz I've been using this foerever; but I'm adding a test and fixing it here: https://github.com/rokucommunity/brighterscript/pull/327

**Comment by TwitchBronBron** [comment]
I ran your test against v0.11.0 (when template strings were first introduced) and this is still present, so I think it has been there from the start. Strange you haven't encountered this before.

**Comment by TwitchBronBron** [comment]
Fixed in #327
