### ISSUE TITLE
File path completion for any string starting with pkg: or libpkg:

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#333]
![image](https://user-images.githubusercontent.com/9591618/109042474-9e744200-76a6-11eb-8932-fec8ba7a7b90.png)
In situations like the above it's likely safe to assume the developer is trying to type a file path in the codebase. We should also offer this type of completion out side of imports.

There are two main file protocols we need to look for at the start of the string. The main one being `pkg:` and the second being `libpkg:`. The second is used in some cases by component libraries.

**Comment by TwitchBronBron** [comment]
@chrisdp the language server doesn't currently support anything other than `pkg:/`, so I can easily add the `pkg:/` completions right now. I need a little more clarification on `libpkg:/`. Should that show all the same files as `pkg:/`? How should the language server handle `libpkg:/` prefixes?

**Comment by chrisdp** [comment]
Pkg: and libpkg: would be treated the same and yes. You would suggest the same files. Libpkg: really would only be used in strings in your code. It's not something you would use in xml. At least not by native components. There is a lot that the Lang server would need to know to suggest one over the other so I would say just go with what ever the developer started with. If your using libpkg it's for a very ￼ specific reason.
