### ISSUE TITLE
Completion error when using callfunc short hand on function

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#352]
I am getting the following completions error for the following code:

error:
```
[Error - 1:10:38 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'functions' of undefined
  Code: -32603 
```

code:
![image](https://user-images.githubusercontent.com/9591618/110509956-109e4b00-80d9-11eb-8d72-b1f3be0f0f42.png)

**Comment by chrisdp** [comment]
Just realizing this is happening on other types of callfunc's and also got this runtime crash in the Program.
The crash above happens on typing the `.` and the crash below happened on typing the `(` resulting in `()`. So going from `m.global.DeviceManager@.updateInstalledChannels` to `m.global.DeviceManager@.updateInstalledChannels()`
New use case: 
![image](https://user-images.githubusercontent.com/9591618/110830573-bedbf900-826f-11eb-88f6-72ffe80eab36.png)

Crash in program:
```
[Error - 1:35:50 PM] error in onSignatureHelp: Cannot read property 'functions' of undefinedTypeError: Cannot read property 'functions' of undefined
    at Program.getStatementsForXmlFile (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.5/node_modules/brighterscript/dist/Program.js:502:69)
    at Program.getSignatureHelp (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.5/node_modules/brighterscript/dist/Program.js:690:38)
    at /Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.5/node_modules/brighterscript/dist/LanguageServer.js:809:134
    at Array.map (<anonymous>)
    at LanguageServer.onSignatureHelp (/Users/chris/.vscode/extensions/rokucommunity.brightscript-2.17.5/node_modules/brighterscript/dist/LanguageServer.js:809:91)
```

**Comment by TwitchBronBron** [comment]
Thanks! This was actually a little more difficult to reproduce that you'd think, because it requires at least one xml component loaded that has no interface defined!
