### ISSUE TITLE
Stop returning completions for complete statements

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#356]
When something like an If statment is complete we should no longer offer completions. For example:
![image](https://user-images.githubusercontent.com/9591618/110834097-80483d80-8273-11eb-9339-57035cea7e5f.png)

**Comment by elsassph** [comment]
I agree I'm often annoyed by those.
Worst offender to me is `function` after `end` which if you trigger insertion of a whole function template...

**Comment by TwitchBronBron** [comment]
This isn't something we can fix with the extension, as completions are sent when you type `t` and then vscode filters them client-side (i.e. the LanguageServer doesn't get subsequent completion requests for `h` `e` `n`). 

However, there's a[ vscode user/workspace setting](https://github.com/microsoft/vscode/issues/24420#issuecomment-303640433) to change the behavior to "smart" which solves this exact issue. 
![image](https://user-images.githubusercontent.com/2544493/111029083-b519d900-83c8-11eb-858f-5448fa2ca759.png)
