### ISSUE TITLE
Files referenced with createChild() are triggering warning BS1013

### ISSUE THREAD

**Issue by jfrux** [rokucommunity/brighterscript#36]
Forgive me if this is too general of an issue and may not be true in all situations but this is just what I'm seeing in this particular codebase I'm working on.  (NOTE: I'm very very new to Roku dev so forgive me if any of this looks silly haha)

```brightscript
' Constants.brs
' ...
    sub Init()
        ' ...
        m.top.something = "something"
        ' ...
    end sub
' ...
```

```brightscript
' SomeFile.brs
' ...
    sub Init()
        ' ...
        m.c = m.top.createChild("Constants")
        ' ...
    end sub
' ...
```

**Comment by TwitchBronBron** [comment]
@chrisdp correct me if I'm wrong, but you would still need to include Constants.brs in an xml file for this to work, right? 

```xml
<!--SomeFile.brs-->
<?xml version="1.0" encoding="utf-8" ?>
<component name="ChildScene" extends="BaseScene"> 
  <script type="text/brightscript" uri="Constants.brs" />
  <script type="text/brightscript" uri="SomeFile.brs" />
</component>
```

**Comment by chrisdp** [comment]
I'm not sure I fully follow the error in this issue. The `createChild` function takes the name of a component like in your example @TwitchBronBron. In that example you would call `m.top.createChild("ChildScene")`

In this context `ChildScene` uses `Constants.brs`, `SomeFile.brs` and any files used by `BaseScene` and its ancestors. 

I assume the warning is being triggered in `Constants.brs` @jfrux?  If so then this file is not being used by a component in the project or there may be an issue in the `bsconfig.json` if you have created one.

**Comment by chrisdp** [comment]
@jfrux if my assumptions are wrong could you post some more details like in what file you are getting the warning? Maybe some of your xml?

**Comment by TwitchBronBron** [comment]
@chrisdp when you call `m.top.CreateChild` with a component name, does that component need to have already been imported like in my example? Because I think that's the issue... It's not being imported, so the compiler recognizes this issue.

**Comment by chrisdp** [comment]
@TwitchBronBron you don't import a component. The component can import scripts in the script tags. So if there is no component in the channel with a proper path to `Constants .brs` then it would show up as unused. Now if he had something like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<component name="Constants"> 
  <script type="text/brightscript" uri="Constants.brs" />
</component>
```

Now he has a `Constants` component. I think there is a bit of confusion on this issue around a script file and a component.

**Comment by TwitchBronBron** [comment]
@chrisdp thanks for the clarification. I got my wires crossed in my brain.

@jfrux that error occurs anytime a script file isn't being imported by any component in the project. So, can you please verify that you are actually importing `Constants.brs` in an xml file in your project somewhere (most likely it should be imported in the `Constants.xml` file where you declare `Constants` as a component)?

**Comment by jfrux** [comment]
Yep. It’s being imported but that file doesn’t extend anything.  So maybe that’s an issue.

Let me get you the xml to show what I mean.

**Comment by jfrux** [comment]
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<component name="Constants" xsi:noNamespaceSchemaLocation="https://devtools.web.roku.com/schema/RokuSceneGraph.xsd">
	<interface>
		<field id="primaryColor" type="color"/>
		<field id="newsyOrange" type="color"/>
		<field id="newsyBlue" type="color"/>
		<field id="overscanPadding" type="assocarray" />
		<field id="rowListConfig"    type="assocarray"/>
	</interface> 
         <script type="text/brightscript" uri="pkg:/components/Constants/Constants.brs" />
</component>
```

Never really seen this done this way so I can't speak to the quality of this code I'm inheriting but I'm sure it could be refactored to make it valid for `bsc`.  Just trying to determine what I should change.

When I make it extend something it seems to not like that lol

**Comment by chrisdp** [comment]
Hummm. And this is the only file getting the 1013 warning? At a glance this all looks right.

**Comment by jfrux** [comment]
Gah... you guys may want to kill me... so we have a set of core files that are getting merged into a directory with the app files and I'm wondering if this was caused by remnants of that process not properly merging them together.

No matter what I do, I can't get it to throw this error again for the life of me.

The only one I'm getting now for that file is:

```
/components/Constants/Constants.xml:1:1 - error BS1007: Component must have an extends attribute.

 1  <component name="Constants" xsi:noNamespaceSchemaLocation="https://devtools.web.roku.com/schema/RokuSceneGraph.xsd">
```

Gah... please forgive me!!!
Still learning... will try to be more careful next time so I don't waste your time.

You all have been so kind and patient.  Thank you!

**Comment by TwitchBronBron** [comment]
@jfrux awesome, I'm glad you figured it out. With how new and buggy the current project is, it's very likely to be bugs, so don't hesitate to keep opening issues, or reach out to us on the #brighterscript channel in the rokudevelopers slack. [rokudevelopers.slack.com](rokudevelopers.slack.com)

**Comment by jfrux** [comment]
That slack is saying this...
![BDD30085-A43C-4613-9F0F-462F80807AE5](https://user-images.githubusercontent.com/171077/74374674-dadf4380-4dac-11ea-9e61-a9011f3d2401.png)

**Comment by TwitchBronBron** [comment]
Hmm. Try this invite link. https://join.slack.com/t/rokudevelopers/shared_invite/enQtMzgyODg0ODY0NDM5LTM0N2UzYWExOGVlMTRlNGI2OTQ0ODA0Y2ZmMzFhZmMwMWEzNWI2MGM1YzFkZDVkZDNiNjYzYTgwODczNGQ2NDY
