### ISSUE TITLE
Completion triggers inside comments

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/brighterscript#362]
Still (or again?) completion list appears after pressing dot while inside a line comment.

**Comment by TwitchBronBron** [comment]
I'm unable to reproduce that. Here's a gif example using extension version 2.17.6:

![9e3ebebf-47fa-485c-a5df-73c652c239ca](https://user-images.githubusercontent.com/2544493/111030294-560b9280-83cf-11eb-818d-a5b7f09f5bb9.gif)

I can trigger the built-in vscode textual completions if I manually activate completions after the dot with ctrl+space, but I don't think that's what you're talking about.

**Comment by elsassph** [comment]
Try without space before the quote, e.g. comment before a function declaration

**Comment by TwitchBronBron** [comment]
None of those seem to trigger it either. 
![ee9c2169-62f7-4f4a-a322-afa020b85046](https://user-images.githubusercontent.com/2544493/111038214-ca592c80-83f5-11eb-8692-d3334480ca64.gif)

**Comment by TwitchBronBron** [comment]
@elsassph are you still seeing this? I can't find a way to reproduce it.

**Comment by elsassph** [comment]
Let's close it until I have a reproduceable case.
