### ISSUE TITLE
error BS1000: Unexpected character '@'

### ISSUE THREAD

**Issue by jfrux** [rokucommunity/brighterscript#37]
```
for each outline in feedXml.body.outline
     ' ...
      display = ValidStr(outline@display) ' throws error BS1000: Unexpected character '@'
     ' ...
end for
```

Any tips on how to re-write this?

**Comment by TwitchBronBron** [comment]
So this is a known issue (#34). That is definitely valid syntax, it's just that our parser doesn't currently support it. We plan on eventually fixing the parser so that is recognized as valid syntax.

In the mean time, you can use `GetAttributes()` to access the attribute. 

```brightscript
 display = ValidStr(outline.GetAttributes().display) 
```
