### ISSUE TITLE
should be able to override class fields

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#391]
Currently classes show a diagnostic whenever a parent and child class have the same property name. I intentially designed the classes this way, but now I'm not seeing much benefit in doing that. 

[here's the code](https://github.com/rokucommunity/brighterscript/blob/d94bfc86b3e2106be2856df5919468770ba828a6/src/validators/ClassValidator.ts#L198). 

We should definitely show diagnostic errors whenever the property types are different between child and parent. However, if the properties are the same type, a child should absolutely be able to re-declare the same property name. 

For example:
```brighterscript
class Parent
    public name = "Mommy"
    public age = 30
end class
class Child
    public name = "Baby" 'this currently produces a diagnostic, but should not
    public age = "0.2" ' this should show a diagnostic because the types aren't the same (don't think it does currently...)
end class
```

Thoughts?

**Comment by georgejecook** [comment]
yes. agree.
I'd also like to know what we think should happen with annotations in that case?
my opinion is that they should be merged, with identical annotations taking precedence from overridden fields.

**Comment by TwitchBronBron** [comment]
Oh man, I completely forgot about annotations! Dang. Yeah, i'll need to look into how to handle those. I'll see how TypeScript does it, hopefully they've figured that problem out and we can just mimic the same functionality.
