### ISSUE TITLE
source literals cause errors in static analysis tool

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#414]
Running the Static analysis tool on transpiled bs files, yields:
```
[ERROR] The use of "file://" has been disabled. Please replace all references to "file://" with the "pkg:/" URL syntax instead.
        Path: /source/mixin/AppService.brs. Line: 146.
[ERROR] The use of "file://" has been disabled. Please replace all references to "file://" with the "pkg:/" URL syntax instead.
        Path: /components/screens/hooks/HookTaskScreen.brs. Line: 37.
[ERROR] The use of "file://" has been disabled. Please replace all references to "file://" with the "pkg:/" URL syntax instead.
        Path: /source/inplayer_entitlements_plugin/InPlayerEntitlementsPlugin.brs. Line: 95.
[ERROR] The use of "file://" has been disabled. Please replace all references to "file://" with the "pkg:/" URL syntax instead.
        Path: /source/zapp-pipes/Client.brs. Line: 68.
```

these `file://` references, come from the bs SOURCE_FILE_PATH  literal.. We either need to fix the literal to produce store-releasable code, or add a warning to the docs to explain to strip these for builds intended for store submission.

**Comment by elsassph** [comment]
Might be wise to avoid inserting `file://` when using the placeholder?

**Comment by georgejecook** [comment]
You'd think; but the issue is that this is the format used by vscode links - so this will break log output navigation in vscode. 

It's gonna need a bit more thought, if we want to keep that (incredibly useful) feature.

**Comment by TwitchBronBron** [comment]
Well their static analysis tool is probably just doing simple context-less regular expression scanning and matches any string that starts with "file:/". To get around this, our source literal can break it up so it avoids detection. George, can you test this avoids detection from the tool?

```
somePath = "file" + ":/whatever....."
```

**Comment by chrisdp** [comment]
Is there a reason the log output isn't just looking for a pkg path in the output? We can easily convert it to file for vs code to use on the extension side.

**Comment by georgejecook** [comment]
![image](https://user-images.githubusercontent.com/1214545/118110799-26830180-b3e3-11eb-912c-124df9cf4657.png)

smart as always @TwitchBronBron  - that does indeed sidestep the issue.

@chrisdp we need to point to file path for transpiled files like bs classes (and other manipulated files that plugins produce)

**Comment by TwitchBronBron** [comment]
I've got a busy day today. @georgejecook do you think you could put up a simple PR to fix this?

**Comment by georgejecook** [comment]
@TwitchBronBron see https://github.com/rokucommunity/brighterscript/pull/415

**Comment by chrisdp** [comment]
@georgejecook This can be closed now correct?
