### ISSUE TITLE
Missing support for the utility functions from the core library v30/bslCore.brs

### ISSUE THREAD

**Issue by lvcabral** [rokucommunity/brighterscript#431]
Functions like the ones below are supposed to be available when a Library is declared:

```
Library "v30/bslCore.brs"

print bslBrightScriptErrorCodes()
print bslUniversalControlEventCodes()
```

Documented at:
https://developer.roku.com/en-gb/docs/references/brightscript/language/component-architecture.md

**Comment by markwpearce** [comment]
Hmm... we could just add the `v30/bslCore.brs` functions as global callables, but that's only accurate when we've loaded it as a library.

RAF's `Roku_Ads()` is currently handled by adding it to the global callables temporarily, until we get `Library` commands properly handled, so I propose we do the same for this Library. Thoughts?

**Comment by TwitchBronBron** [comment]
Yes, I agree. Let's just add them to the global callables for now. I have intentions of checking for library statements to detect when we should include them...but this is the quick fix, and we can circle back around to that when we have less important things to work on.
