### ISSUE TITLE
Add "Brighterscript" to Github's Linguist

### ISSUE THREAD

**Issue by markwpearce** [rokucommunity/brighterscript#451]
It would be great if Brighterscript was listed as a real language in Github repos!

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by elsassph** [comment]
Yeah I've looked into that, but to make a PR to just associate `.bs` with the BrightScript syntax you need to prove that there are "hundreds" of repositories using it...
```
- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      <!-- Replace FOOBAR with the new extension, and KEYWORDS with keywords unique to the language. Repeat for each extension added. -->
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
```
Then if you actually search, I could find another language using `.bs` (and a `bsc` compiler :D)... https://github.com/B-Lang-org/bsc

TBH the real deal is that we should seriously look again at using `.brs` even for `brighterscript` code...

**Comment by TwitchBronBron** [comment]
This was resolved by https://github.com/github/linguist/pull/5643
