### ISSUE TITLE
Detect too-deep nested folder structure

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#464]
roku will not read files that are >= 8 directories deep like so:
![image](https://user-images.githubusercontent.com/2544493/138951853-1c5a0b3a-e115-4dc2-8a0c-153638d9bd7a.png)

We should determine the edge cases for this, and then add diagnostics for the `destPath`  on files that are too nested.

Here are the tests that have been verified
- components living in the 8th directory or deeper will not compile.
    - `/components/modules/Test/Test/Test/Test/CustomProgressBar/CustomProgressBar.xml` (WORKS)
   - `/components/modules/Test/Test/Test/Test/Test/CustomProgressBar/CustomProgressBar.xml` (FAILS)
- images can be loaded at any directory level
   - used in `<poster>` node (WORKS)
   - used in `manifest` as the splash image (WORKS)
- scripts at any level can be imported into components 
  -  `<script uri="pkg:/components/modules/Test/Test/Test/Test/Test/Dummy/Dummy.brs">` (WORKS)

From all of these tests, it appears the issue is that that the BrightScript compiler file auto-discovery algorithm limits itself to 7 directories deep...but the files themselves still exist and can be directly referenced by uri-style references. 

Here are the restrictions we need to guard against:
 - `.xml` files in the `pkg:/components` folder should be flagged if they are 8 or more directories deep
 - `.brs` and `.bs` files in the `pkg:/source` folder should be flagged if they are 8 or more directories deep

**Comment by iObject** [comment]
Note: This does not reflect images. Included ones referenced in the manifest.
