### ISSUE TITLE
Walk functionality should return the key path from the parent to the child

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#477]
All of the walk callbacks should provide a way to get from the parent to that child. Like a string key path. For instance, `'Block.statements[0].name'`

**Comment by elsassph** [comment]
Are you facing a specific need for that? AST changes that I did were done in order to not need this kind of information as it's costly to build and expensive to use.

**Comment by TwitchBronBron** [comment]
I don't think I explained this overly well. Opening this ticket was mostly just so I didn't forget about it. :D 

I just submitted PR #478 which adds support for editing the AST. However, when removing AST elements temporarily with the code from #478, using the visitor pattern isn't helpful. Consider this example. 

```typescript
import { CompilerPlugin, BeforeFileTranspileEvent, isBrsFile, WalkMode, createVisitor, TokenKind } from './';
// plugin factory
export default function () {
    return {
        name: 'removePrint',
        // transform AST before transpilation
        beforeFileTranspile: (event: BeforeFileTranspileEvent) => {
            if (isBrsFile(event.file)) {
                event.file.ast.walk(createVisitor({
                    PrintStatement: (stmt, parent) => {
                        //remove every print statment.....how?
                    }
                }), {
                    walkMode: WalkMode.visitStatementsRecursive
                });
            }
        }
    } as CompilerPlugin;
};
```
In this example, we have the print statement, and its parent statement. However, we don't have a key that lets us find the PrintStatment in the parent, which then prevents us from registering a "remove the statement" change in the `astEditor` object. 

Since the `parent` param in visitor is not always the direct owning parent of the statement, I'm going to make this change:

```typescripth
//this
function visitor(stmtExpr, parent);
//becomes this
function visitor(stmtExpr, parent, owningObject, key)
```

where owningObject is the direct owning parent object of the stmtExpr, and key is how you access it. For example:
```typescript
//PrintStatement
visitor(this.expressions[i], this, this.expressions, i)
```
