### ISSUE TITLE
Empty If Block Invalid Warning

### ISSUE THREAD

**Issue by triwav** [rokucommunity/brighterscript#48]
In if block if you have an empty body for one of the statements it throws 1081 Found unexpected token 'else'
![image](https://user-images.githubusercontent.com/1753881/79009747-43893900-7b2e-11ea-98e1-9fbccbf66e6a.png)

**Comment by TwitchBronBron** [comment]
The same problem happens for empty else blocks.
![image](https://user-images.githubusercontent.com/2544493/79035267-ca6bff00-7b8a-11ea-8bc0-b189a01bbcc6.png)
