### ISSUE TITLE
Const compilation issue

### ISSUE THREAD

**Issue by tomek-r** [rokucommunity/brighterscript#666]
Hey
I am experiencing some issues when working with consts
```javascript
Error when calling plugin BscPlugin.beforeFileTranspile: TypeError: Cannot read property 'getConstFileLink' of undefined at BrsFilePreTranspileProcessor.processExpression (/node_modules/brighterscript/dist/bscPlugin/transpile/BrsFilePreTranspileProcessor.js:70:46
```
brighterscript version is 0.55.0
the code:
```brightscript
namespace Settings
    const KEY = "Key"
end namespace
```
It compiles after all but produces the error. I have no additional plugins installed.

**Comment by TwitchBronBron** [comment]
I can't seem to reproduce this. Would you be able to put together either
a) some steps on how to reproduce this issue?
b) a small sample app that reproduces the issue?

**Comment by xgouchet** [comment]
I'm running on the same issue when I started setting up `bslint` + `roca`. 

Because I want `bslint` to apply on my test files as well, I'm using the following `bsconfig.json`: 

```json
{
    "rootDir": "src",
    "files": [
        "manifest",
        "source/**/*.*",
        "components/**/*.*",
        "images/**/*.*",
        "tests/**/*.*"
    ],
    "plugins": [
        "@rokucommunity/bslint"
    ]
}
```

And then in my `src/tests` folder, I have a sample `roca` test: 

```brightscript
function main(args as object) as object
    return roca(args).describe("test suite", sub()
        m.pass()
    end sub)
end function
```
