### ISSUE TITLE
Autocomplete on `m.` and `end function` reportedly causing issues for some users.

### ISSUE THREAD

**Issue by jfrux** [rokucommunity/brighterscript#67]
![mismatch-autocomplete-vscode-brightscript](https://user-images.githubusercontent.com/171077/80388519-fc15e300-8877-11ea-83cc-524452b3ca49.gif)

**Comment by TwitchBronBron** [comment]
I played with the typescript language service a little bit, and they return all of the valid keywords for any completion not next to a dot. 

I will enhance the completion engine to return all of the known keywords, and also `m` when the cursor is found within a function.
