### ISSUE TITLE
False positive on diagnostic referencedConstDoesNotExist when const is defined in manifest

### ISSUE THREAD

**Issue by xgouchet** [rokucommunity/brighterscript#676]
I have an app with a constant defined in the manifest: 

```
bs_const=foo=true
```

Then I have a brightscript file using it as such: 

```brightscript
sub something()
    #if foo
        print "foo is true"
    #end if 
end sub
```

But running `bsc`, I get the following error: 

> src/source/foo.brs:19:9 - error BS1090: Referenced #const does not exist

**Comment by TwitchBronBron** [comment]
Currently brighterscript (incorrectly) treats `bs_const` variables in a case-sensitive manner (i.e. `foo` and `FOO` are treated as separate variables). 

Can you verify this is actually your problem? Your current example uses lower case for both, which doesn't trigger any errors in my testing. but if I define `bs_const=FOO=true` and reference it like `#if foo` then I _do_ get the error.
