### ISSUE TITLE
Const do not work with template strings

### ISSUE THREAD

**Issue by iBicha** [rokucommunity/brighterscript#733]
const SOMETHING = "SOMETHING"
const SOMETHING2 = "SOMETHING2"

```
`${SOMETHING}-${SOMETHING2}`
```

does not lead to "SOMETHING-SOMETHING2"

**Comment by TwitchBronBron** [comment]
What version of brighterscript are you using? I just tested using brighterscript@0.60.4 in the [brighterscript-template](https://github.com/rokucommunity/brighterscript-template) project with your example, and it seems to work fine. 

![image](https://user-images.githubusercontent.com/2544493/198886036-52fe3773-5216-49b2-9d7a-8d872baa7dca.png)

**Comment by iBicha** [comment]
You're right, I was on `"brighterscript": "0.52.3",`, updating fixed the issue.
Thanks @TwitchBronBron

**Comment by TwitchBronBron** [comment]
Great! Yeah we fixed a few template string bugs since 0.52.3. Glad it's working for you now.
