### ISSUE TITLE
Add roCECStatus as valid createObject param value

### ISSUE THREAD

**Issue by triwav** [rokucommunity/brighterscript#735]
I'm incorrectly getting `Unknown BrightScript component 'roCECStatus'`. For a line like `createObject("roCECStatus")`. We should add this as a valid component.

**Comment by markwpearce** [comment]
It's listed as `toCECStatus` on the docs page in the sidebar... that's probably why it complains.

**Comment by TwitchBronBron** [comment]
@markwpearce I looked through the generated json for this, and I don't even see "roCECStatus" as a component anywhere. The only thing close is `rocecstatusevent` which is not the same thing.

**Comment by markwpearce** [comment]
Fixed here: https://github.com/rokucommunity/brighterscript/pull/736
