### ISSUE TITLE
add a warning if callfunc/@ is called with more than 5 parameters

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/brighterscript#760]
I'm not sure about the cause of this limitation, but, apparently, it's not possible to call a function of a node with more that 5 parameters. If I do it, my channel stops, and, half of the times, my roku devices crashes and reset.

It would be useful to add some linters/compiler warnings about 
- defining a function in a component (exposed in the `<interface />`) with more than 5 parameters
- calling `node@.function(...)` / `node.callfunc("function", ...)` with more than 5/6 parameters

**Comment by iObject** [comment]
@ZeeD Great suggestion.  Working on this now.
