### ISSUE TITLE
Facing No Addon found for Widevine exception when trying to play Drm content

### ISSUE THREAD

**Issue by AmanPunjWynk** [rokucommunity/brighterscript#767]
Hi Team, I am facing "No Addon found for Widevine exception" when trying to play DRM content.

How I am getting this error:-

I restore my Roku Ultra Device. Sign in with user. launch my app and trying to play DRM content.
Error Thrown :- no addon found for Widevine, DRMerrorcode:0, errocode:1

How I fixed for local device:-

as I observed that While making DRM connection some parameters are missing/ not downloaded. so I'll just first launch YouTube channel play one video so that required parameters to play Widevine content will get downloaded in my device.

now if I try to play content. Content is playing Perfectly.

Blocker I am facing:- when I am uploading my package for channel behaviour testing.. deep linking Tests are failing because content is not playing because of this error.

I have attached a Screenshot of error from my application. Any suggestion or guidance will be helpful.

<img width="1204" alt="Screenshot 2022-12-23 at 3 10 33 PM" src="https://user-images.githubusercontent.com/105850825/211200102-9c173490-0afa-4a0b-9c19-5b3b0882a165.png">

**Comment by TwitchBronBron** [comment]
This appears to be a general Roku programming question, and as such, I don't think it relates to his repository. Feel free to raise your question in the #general channel in our community slack (link can be found at the top of this project readme).
