### ISSUE TITLE
Missing ? in final optional chaining transpiled output

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#770]
![image](https://user-images.githubusercontent.com/2544493/212396922-cb84a6a1-191d-4861-b200-38a6024f7924.png)

Notice how the final `?` is missing in `visible.ither`

**Comment by tomek-r** [comment]
hey @TwitchBronBron 
```brightscript
m?.something?.something = false
```
is illegal syntax. It would mean you can assign `false` to `Invalid` value. This will trigger a crash on roku box. 

Instead, this should show an error and highlight in red.

https://developer.roku.com/en-gb/docs/references/brightscript/language/expressions-variables-types.md#optional-chaining-operators

```brightscript
x = array?[12]          ' Supported
array?[12] = x          ' Not supported
x = f?()                      ' Supported
f?()                            ' Not supported
```

**Comment by TwitchBronBron** [comment]
@tomek-r this PR will resolve your request to flag the invalid syntax.

https://github.com/rokucommunity/brighterscript/pull/782
