### ISSUE TITLE
disable next line doesn't seem to work

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#84]
```    
'bs:disable-next-line
 m.top.sdkTask.exit = true
```

still results in error

**Comment by TwitchBronBron** [comment]
@georgejecook is this still an issue?

**Comment by markwpearce** [comment]
this is still an issue... with Brightscript language extension 2.1.21 (uses brightscript@0.10.0) 

```bs
  'bs:disable-next-line
  Dim requestData[requestList.count()]
```
still results in error (Found unexpected token 'Dim')

**Comment by TwitchBronBron** [comment]
@markwpearce can you provide any additional steps to reproduce? This works just fine for me. 
![ignore line bs comment](https://user-images.githubusercontent.com/2544493/83355562-2e5ea880-a32e-11ea-91d4-c2842d2f45f6.gif)

**Comment by TwitchBronBron** [comment]
I have refactored the disable comments to support leading whitespace, and also to utilize the tokenizer instead of splitting the source file by newline and manually parsing it. Hopefully one of these two things has resolved your issue. #108

**Comment by TwitchBronBron** [comment]
@markwpearce any updates on this?

**Comment by markwpearce** [comment]
Running version 2.4.4, it still shows up as a "problem" with red underline in vs Code.

```brs
sub testDimNoDisable()
  dim array[3]
end sub

sub testDimWithDisable()
  'bs:disable-next-line
  dim array[3]
end sub
```

Both of the "dim" statements above get the red underline, with 

{
	"resource": "test.brs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1081",
	"severity": 8,
	"message": "Found unexpected token 'dim'",
	"source": "brs",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 2,
	"endColumn": 6
}

**Comment by TwitchBronBron** [comment]
@markwpearce is this still an issue?

**Comment by markwpearce** [comment]
Nope! I'll close it
