### ISSUE TITLE
callfunc doesn't work with no args defined

### ISSUE THREAD

**Issue by kbunch** [rokucommunity/brighterscript#857]
ex: 

function test()
..
end function 

node@.test()

**Comment by kbunch** [comment]
@TwitchBronBron when/where does this happen? we use callFunc with no params all over the place in our code

**Comment by TwitchBronBron** [comment]
This happened consistently when brighterscript was first released (around 2019). Recently I've been hearing that it's no longer an issue, we just haven't gotten around to doing full testing and updating brighterscript to remove this requirement. 

I'd be open to reviewing a PR that adds a bsconfig.json option for disabling this feature on a per-project basis if you're interested?

**Comment by kbunch** [comment]
@TwitchBronBron I'd be interesting it adding a PR once we get into it. Right now evaluating it to see if we want to use it on a large project. Right now we are all vanilla Brightscript.

**Comment by TwitchBronBron** [comment]
The v1 branch has removed this requirement, so I'm going to close this as we'll eventually "fix" it.
