### ISSUE TITLE
Breakpoints are ignored

### ISSUE THREAD

**Issue by rrirower** [rokucommunity/brighterscript#863]
Using vscode on Windows, I've used the following bsconfig to define my setup:

```
{
    "rootDir": "..\\DptoSceneGraph",
    "files": [
        "source/**/*",
        "components/**/*",
        "images/**/*",
        "manifest"
    ],    
    "stagingDir": "debug",
    "retainStagingFolder": true,
    "createPackage": false,
    "sourceMap": true
}
```
When I set breakpoints, they appear to be ignored.  The red dot indicating the existence of a breakpoint reverts to an open circle and the breakpoint is never set.

**Comment by TwitchBronBron** [comment]
Can you share your `launch.json` from vscode? I'm thinking it might be misconfigured. 

You can compare your project's `launch.json` to this [brighterscript-template](https://github.com/rokucommunity/brighterscript-template) project which is correctly configured to work with vscode.

**Comment by rrirower** [comment]
I think you were right. I redid the launch file and it seems to work now.

**Comment by TwitchBronBron** [comment]
Great!
