### ISSUE TITLE
interfaces doesn't show up in layout view

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/brighterscript#873]
(I don't know if this issue should be opened here on the vscode plugin project, feel free to close/move it if appropriate)

if I use `bsc --lsp` as language server, in my IDE I don't see any reference to the [interfaces](https://github.com/rokucommunity/brighterscript/blob/master/docs/interfaces.md) I've defined in the file.

I can reproduce the same issue on VSCode

<img width="448" alt="immagine" src="https://github.com/rokucommunity/brighterscript/assets/69095/6fbf0f64-2047-4bac-b2fa-c8b6e5b2517d">

**Comment by TwitchBronBron** [comment]
This should be fixed in the next upcoming release of brighterscript, thanks to https://github.com/rokucommunity/brighterscript/pull/1116 and https://github.com/rokucommunity/brighterscript/pull/1118
