### ISSUE TITLE
Copy BrightScript folder to another folder hangs debugger

### ISSUE THREAD

**Issue by rrirower** [rokucommunity/brighterscript#878]
I copied my entire BrightScript project folder to another folder so I could make changes without affecting the original code.  I changed the bsconfig.json file to point to the new folder path.  I am running BSC 0.65.4.

When I try to debug, the breakpoint is hit, but, the debugger hangs trying to display local variables.

What am I doing incorrectly?

**Comment by TwitchBronBron** [comment]
We've squashed several bugs in the debugger related to that variables panel spinning. Are you still seeing this issue?

**Comment by rrirower** [comment]
The spinning variable issue seems to be resolved.  

I have one remaining issue that's a PIA.  During a typical debugging session, the debugger will either begin and exit after a short time.  Or, not start at all and claim that the App exited without user interaction.

**Comment by TwitchBronBron** [comment]
Are you using telnet or debug protocol?

**Comment by rrirower** [comment]
`"enableDebugProtocol": true,`

**Comment by TwitchBronBron** [comment]
Okay. Yeah, there are still some quirks around that. sometimes Roku doesn't respond to the debug protocol connection request. I have some work in progress to fix that. I'm going to close this issue because that is a known issue that I'm working on. :)
