### ISSUE TITLE
Validate class member assignment type mismatch

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#879]
With the new type validations in v0.66.0 alphas, we should be able to assign a specific type to classes, and therefore validate type mismatches for class members. Line 3 should be an error because we're assigning an integer to a string.

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/19fa45fd-3021-4010-bea2-58024a6206cd)

**Comment by markwpearce** [comment]
If lhs of assignment is a dotted get expression, then we can use isTypeCompatible of left vs. The rhs type. This should also catch when we do assignments for components to make sure the type is correct

**Comment by markwpearce** [comment]
Fixed with https://github.com/rokucommunity/brighterscript/commit/a2c153aff1be92b4b50e909cda62b2c0179cf70c

**Comment by markwpearce** [comment]
closed
