### ISSUE TITLE
Adding string and number should be compile error

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#880]
With the new type validations in v0.66.0, this should be a compile error because you can't add a string and an int. 

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/0d53ba62-3b32-45a8-a5a4-936b542b1aa9)

**Comment by markwpearce** [comment]
In scope validate’s ast walk, visit binaryOperator expressions, and if neither LHS or RHS are dynamic type, and the util function that finds binary operator results return dynamic type, then raise a new diagnostic… Something like “Operator $operator can not be used with types $lhs and $rhs”

**Comment by markwpearce** [comment]
Solved in https://github.com/rokucommunity/brighterscript/commit/7cafaf12219dcfa73b3e0be04f7acba47b10f93a
