### ISSUE TITLE
Reduce like types for hovers

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#881]
When hovering over arrays in v0.66.0 branch, we should reduce types that are the same. 

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/7f27f9e9-9d77-469e-91aa-fd910b5247ee)

I'd expect that to be `Array<integer>` (one `integer` not three)

**Comment by markwpearce** [comment]
Should use this.defaultType instead of innerTypes.map(…)

**Comment by markwpearce** [comment]
Solved https://github.com/rokucommunity/brighterscript/commit/69d3037e6a5bd3ad9ae2a422e03d2ad9d3e2ca8c
