### ISSUE TITLE
Completion on union type should only show shared properties

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#882]
Leveraging the v0.66 type system, I would expect the completions on a union type to show the shared properties from that union. In the below example, I should see "url" as the only completion option, not the fallback to all text in file.
![image](https://github.com/rokucommunity/brighterscript/assets/2544493/421b2b05-b0e0-4d11-8e4d-ed2af4c74eec)

**Comment by markwpearce** [comment]
solved https://github.com/rokucommunity/brighterscript/commit/69d3037e6a5bd3ad9ae2a422e03d2ad9d3e2ca8c
