### ISSUE TITLE
Completions for enum is wrong

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#883]
Completions on an enum type should reflect the underlying enum member's completions, not the enum member list. This should treat `button` like a string with respect to completions.

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/92ce63a9-793c-4a4e-a497-6c4b4776536d)

**Comment by markwpearce** [comment]
solved https://github.com/rokucommunity/brighterscript/commit/69d3037e6a5bd3ad9ae2a422e03d2ad9d3e2ca8c
