### ISSUE TITLE
Validation Cycle seems off

### ISSUE THREAD

**Issue by markwpearce** [rokucommunity/brighterscript#886]
It seems like the validation cycle is wrong somehow.

I think what’s happening is it only validates on a keypress if that keypress was after a certain length of time:

this will cause validation:
`<typing really fast> <wait> <press one key>`

this will not cause validation:
`<typing really fast> <wait>`

**Comment by TwitchBronBron** [comment]
Can't reproduce anymore. So we fixed it?
