### ISSUE TITLE
interface validations should not warn for extraneous properties

### ISSUE THREAD

**Issue by TwitchBronBron** [rokucommunity/brighterscript#899]
It appears that interface validations for AAs passed to functions are incorrectly warning about when interfaces have extra properties not found on the interface. 

In this example, it's totally valid to pass an AA that has `beta2` property. The error should be that `charlie` is missing.

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/3780a13b-6138-4198-b8ee-822b2a03f35e)

**Comment by markwpearce** [comment]
I don't think this is a valid issue? The error I'm curently seeing on 0.66.0-alpha-6 looks correct

![image](https://github.com/rokucommunity/brighterscript/assets/810290/5b06dbe3-1101-46e0-86ec-3ecbea80a01b)
