### ISSUE TITLE
Syntax highlighting for Native Component Types

### ISSUE THREAD

**Issue by markwpearce** [rokucommunity/brighterscript#905]
If you use a type like `roSGNodePoster`,  the syntax coloring should be the same as for Classes or Interfaces.

**Comment by TwitchBronBron** [comment]
This can be solved in the `BrsFileSemanticTokensProcessor`

**Comment by TwitchBronBron** [comment]
Honestly, I think that entire file should be overhauled to lean heavily into the new type system. I think a lot of that logic can be simplified.
